# Generated by Django 5.2 on 2025-05-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_is_published'),
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('-list_date',)},
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['list_date'], name='listings_li_list_da_153ce3_idx'),
        ),
    ]
